const mongoose=require('mongoose')
const KidneyTestSchema=new mongoose.Schema({

            organization_name:{
                type:String
            },
            patient_id:{
                type:String
            },
            report_date:{
                type:String
            },
            test_name:{
                type:String
            },
            colour:{
                type:String
            },
            appearance:{
                type:String
            },
            specificgravity:{
                type:String
            },
            pH:{
                type:String
            },
            glucose:{
                type:String
            },
            protein:{
                type:String
            },
            ketones:{
                type:String
            },
            blood:{
                type:String
            },
            bilirubin:{
                type:String
            },
            urobilinogen:{
                type:String
            },
            leucocyte_esterase:{
                type:String
            },
            nitrite:{
                type:String
            },
            pus_cells:{
                type:String
            },
            redbloodcells:{
                type:String
            },
            epithelialcells:{
                type:String
            },
            casts:{
                type:String
            },
            crystals:{
                type:String
            },
            yeast:{
                type:String
            },
            bacteria:{
                type:String
            },

            des:{
                type:String
            }
});
const k=mongoose.model('k',KidneyTestSchema,'patients');
module.exports=k;
